# MongoDB Atas SRV connection string
server.port=8080
spring.data.mongodb.uri=mongodb+srv://Mohanbudhireddy:Mohan2004@cluster0.urlwavv.mongodb.net/outpass_project?retryWrites=true&w=majority
spring.main.banner-mode=off
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

#spring.thymeleaf.prefix=classpath:/frontend/

