# MongoDB Atas SRV connection string
server.port=8080
spring.data.mongodb.uri="your url"
spring.main.banner-mode=off
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

#spring.thymeleaf.prefix=classpath:/frontend/

